Repository SkywardAI/kirin, pull requests merged in 2024-03, with the labels that each got.

#24 chore: add frontend docker image to the docker-compose
  docker-compose.yaml
Labels: enhancement

#28 Updated README.md
  README.md
Labels: documentation, enhancement

#32 [ci]Add version list
  .github/release-drafter.yml
Labels: enhancement, CI

#45 [draft]:remove ml libraries
  backend/requirements.txt
  backend/src/repository/rag/chat.py
  backend/src/utilities/devices/devices.py
Labels: python, dependencies, deep-learning
