Repository SkywardAI/kirin, pull requests merged in 2024-04, with the labels that each got.

#72 Replace base image
  LICENSE.md
  backend/Dockerfile
  backend/pyproject.toml
  backend/requirements.txt
  backend/src/config/settings/base.py
Labels: build, container

#73 Bump base image version
  backend/Dockerfile
Labels: api, build, container

#80 Merge Dev to main branch for muilple changes
  .env.example
  .gitignore
  README.md
  backend/Dockerfile
  backend/src/config/settings/base.py
  backend/src/config/settings/const.py
  backend/src/repository/ai_models.py
  backend/src/repository/events.py
  backend/src/repository/rag/__init__.py
  backend/src/repository/rag/chat.py
  backend/src/repository/vector_database.py
  docker-compose.demo.yaml
  docker-compose.yaml
Labels: python, api, deep-learning, vector db

#85 add demo which start containers without building
  .github/workflows/ci-backend.yaml
  Makefile
  backend/src/repository/ai_models.py
  docker-compose.demo.yaml
  docker-compose.yaml
Labels: api, build, container

#89 Add docker-compose as dev env and remove transformers
  .devcontainer/devcontainer.json
  .devcontainer/docker-compose.yml
  .github/workflows/ci-backend.yaml
  .gitignore
  .vscode/launch.json
  .vscode/settings.json
  backend/Dockerfile
  backend/requirements.txt
  backend/src/__init__.py
  backend/src/config/settings/base.py
  backend/src/repository/ai_models.py
  backend/src/utilities/devices/__init__.py
  backend/src/utilities/devices/devices.py
  backend/tests/conftest.py
  backend/tests/unit_tests/test_src.py
  codecov.yaml
Labels: CI, python, api, deep-learning

#87 update the Rebel v0.1.3.
  docker-compose.yaml
Labels: container

#97 fix issue for ci and release drafter
  .github/release-drafter.yml
  .github/workflows/ci-backend.yaml
Labels: ci

#101 remove tag template emoji
  .github/release-drafter.yml
Labels: ci, patch

#103 Bump deployment version and append files to dockerignore
  .dockerignore
  backend/Dockerfile
  docker-compose.demo.yaml
Labels: build, container

#102 Fix the wrong ci name
  .github/workflows/ci-backend.yaml
  .vscode/launch.json
Labels: ci, patch

#107 Replacing repo secrets to org level secrets
  .github/workflows/ci-backend.yaml
Labels: ci

#98 feat/add api of listing used datasets
  backend/src/api/routes/file.py
  backend/src/api/routes/train.py
  backend/src/models/schemas/train.py
Labels: python, api

#105 Added code of conduct, contribution and made changes to Readme.md
  CODE_OF_CONDUCT.md
  CONTRIBUTION.md
  README.md
Labels: documentation, enhancement, patch

#113 fix/remove the init of model when start application
  backend/Dockerfile
  backend/requirements.txt
  backend/src/config/settings/const.py
  backend/src/repository/rag/__init__.py
Labels: api, patch

#104 Add logs command in Makefile
  Makefile
Labels: container

#119 Remove requirements.txt and bump base image's version
  .github/workflows/ci-backend.yaml
  README.md
  backend/Dockerfile
  backend/README.md
  backend/pyproject.toml
  backend/requirements.txt
Labels: ci, build, container

#116 feat/use kimchima chat_summary to gernarate_answer
  backend/Dockerfile
  backend/src/config/events.py
  backend/src/config/settings/const.py
  backend/src/repository/ai_models.py
  backend/src/repository/events.py
  backend/src/repository/rag/__init__.py
  backend/src/repository/rag/chat.py
Labels: python, api, deep-learning

#124 Feat/model
  backend/Dockerfile
  backend/src/config/settings/const.py
  backend/src/repository/ai_models.py
  backend/src/repository/rag/chat.py
Labels: enhancement, api, deep-learning

#133 [chat-backend] Implemented issue templates and SECURITY.md
  .github/ISSUE_TEMPLATE/1-issue.yml
  .github/ISSUE_TEMPLATE/2-feature.yml
  .github/ISSUE_TEMPLATE/3-bug.yml
  .github/ISSUE_TEMPLATE/config.yml
  SECURITY.md
Labels: documentation, enhancement

#129 Feat/con
  backend/Dockerfile
  backend/src/api/routes/chat.py
  backend/src/config/settings/const.py
  backend/src/main.py
  backend/src/repository/ai_models.py
  backend/src/repository/conversation.py
  backend/src/repository/crud/base.py
  backend/src/repository/crud/chat.py
  backend/src/repository/database.py
  backend/src/repository/events.py
  backend/src/repository/rag/chat.py
Labels: api, deep-learning, vector db
