Repository SkywardAI/kirin, pull requests merged in 2024-07, with the labels that each got.

#181 Add docker series tools version
  .github/workflows/ci-backend.yaml
  .github/workflows/release-drafter.yml
  README.md
  backend/Dockerfile
  backend/pyproject.toml
  backend/sample_files/sample.csv
  docker-compose.yaml
  docs/Requirements.md
Labels: enhancement, ci, build, container

#183 add instruction for inference
  Makefile
  backend/src/repository/rag/chat.py
  docs/Development.md
Labels: api, deep-learning, cpus

#195 remove frontend
  docker-compose.demo.yaml
  docker-compose.gpu.yaml
  docker-compose.yaml
Labels: container

#197 Bump docker-compose to v2
  Makefile
  docs/Requirements.md
Labels: container

#211 feat:Add interface description
  backend/src/models/schemas/account.py
  backend/src/models/schemas/ai_model.py
  backend/src/models/schemas/chat.py
  backend/src/models/schemas/data_analyze.py
  backend/src/models/schemas/dataset.py
  backend/src/models/schemas/file.py
  backend/src/models/schemas/jwt.py
  backend/src/models/schemas/train.py
  backend/src/models/schemas/version.py
Labels: documentation, apis

#212 support stream
  backend/src/api/routes/chat.py
  backend/src/models/schemas/chat.py
  backend/src/repository/rag/chat.py
Labels: apis

#225 fix stream output
  backend/src/repository/rag/chat.py
Labels: apis

#226 Make code more stable with stream request
  backend/src/api/routes/chat.py
  backend/src/repository/rag/chat.py
Labels: apis

#230 release new version
  Makefile
  docker-compose.demo.yaml
Labels: apis

#231 Update README.md with a video demo
  README.md
Labels: documentation, enhancement

#234 Add parameters to chat API
  README.md
  backend/src/api/routes/chat.py
  backend/src/models/schemas/chat.py
  backend/src/repository/rag/chat.py
  docker-compose.demo.yaml
  docker-compose.gpu.yaml
  docker-compose.yaml
Labels: apis

#235 Add healthy check
  backend/Dockerfile
  backend/src/api/endpoints.py
  backend/src/api/routes/health.py
  docker-compose.demo.yaml
Labels: apis, container

#238 Fix the wrong link of License
  README.md
Labels: documentation

#243 Feat/api new apis for save chat histor and update session info
  backend/src/api/routes/chat.py
  backend/src/models/db/chat.py
  backend/src/models/schemas/chat.py
  backend/src/repository/crud/chat.py
  backend/src/utilities/exceptions/http/exc_404.py
  backend/src/utilities/messages/exceptions/http/exc_details.py
Labels: apis

#247 Add resource reservations for inference container
  Makefile
  docker-compose.demo.yaml
  docker-compose.gpu.yaml
  docker-compose.yaml
Labels: container

#248 remove check n_keep at the initial stage
  backend/src/repository/events.py
  backend/src/repository/inference_eng.py
  backend/src/repository/rag/chat.py
  backend/src/utilities/httpkit/__init__.py
  backend/src/utilities/httpkit/method_kit.py
  backend/tests/unit_tests/test_method_kit.py
Labels: apis

#255 Fix devcontainer and bump version
  .devcontainer/devcontainer.json
  Makefile
  backend/Dockerfile
  docker-compose.yaml
Labels: apis, container

#257 Remove python-jose and add test cases
  .devcontainer/devcontainer.json
  .vscode/settings.json
  Makefile
  backend/pyproject.toml
  backend/requirements.txt
  backend/src/securities/authorizations/jwt.py
  backend/tests/unit_tests/test_jwt.py
  backend/tests/unit_tests/test_method_kit.py
Labels: enhancement, apis, test

#258 Add unittest in makefile, CI and replace attributes of API aggregator
  .github/workflows/linter-and-builder.yaml
  Makefile
  backend/src/api/routes/version.py
  backend/src/config/settings/base.py
  backend/src/config/settings/development.py
  backend/src/main.py
  backend/src/repository/database.py
  backend/src/repository/inference_eng.py
  backend/src/repository/rag/chat.py
  backend/tests/unit_tests/test_method_kit.py
  backend/tests/unit_tests/test_src.py
Labels: apis

#267 Add Documentation for API Endpoints
  backend/src/api/routes/account.py
  backend/src/api/routes/ai_model.py
  backend/src/api/routes/authentication.py
  backend/src/api/routes/file.py
  backend/src/api/routes/train.py
Labels: documentation, enhancement, apis

#270 Feat/test
  Makefile
  README.md
  backend/src/api/endpoints.py
  backend/src/api/routes/account.py
  backend/src/api/routes/ai_model.py
  backend/src/api/routes/authentication.py
  backend/src/api/routes/version.py
  backend/src/config/settings/base.py
  backend/src/main.py
  backend/src/models/schemas/version.py
  backend/src/repository/database.py
  backend/tests/unit_tests/test_api_authentication.py
  backend/tests/unit_tests/test_api_version.py
  backend/tests/unit_tests/test_src.py
  docker-compose.demo.yaml
  docker-compose.gpu.yaml
  docker-compose.yaml
Labels: enhancement, python, test

#275 fix incorrect parameters
  backend/src/config/events.py
  backend/src/repository/events.py
  backend/src/repository/inference_eng.py
  backend/src/repository/rag/chat.py
Labels: python

#279 Add RAG and datasets API
  Makefile
  backend/Dockerfile
  backend/pyproject.toml
  backend/requirements.txt
  backend/src/api/endpoints.py
  backend/src/api/routes/chat.py
  backend/src/api/routes/rag_datasets.py
  backend/src/config/settings/base.py
  backend/src/config/settings/const.py
  backend/src/models/schemas/dataset.py
  backend/src/repository/crud/vectors_helper.py
  backend/src/repository/inference_eng.py
  backend/src/repository/rag/chat.py
  backend/src/repository/rag_datasets_eng.py
  backend/src/repository/vector_database.py
  docker-compose.demo.yaml
  docker-compose.yaml
Labels: apis, dataset

#281 Add unit test for health check
  backend/tests/unit_tests/test_api_health.py
Labels: test

#283 Add optional collection name field for chating
  backend/src/api/routes/chat.py
  backend/src/models/schemas/chat.py
  backend/src/repository/rag/chat.py
Labels: python, apis

#289 Set collection name default value to None
  Makefile
  backend/src/models/schemas/chat.py
  backend/tests/unit_tests/test_api_version.py
Labels: apis

#304 Fix the key word type was used as session type
  backend/src/api/routes/chat.py
  backend/src/api/routes/rag_datasets.py
  backend/src/config/events.py
  backend/src/config/settings/const.py
  backend/src/models/db/chat.py
  backend/src/models/db/dataset.py
  backend/src/models/schemas/chat.py
  backend/src/repository/crud/chat.py
Labels: apis, dataset

#305 Add load/list RAG datasets
  Makefile
  backend/src/api/routes/rag_datasets.py
  backend/src/config/settings/base.py
  backend/src/models/db/dataset.py
  backend/src/models/schemas/dataset.py
  backend/src/repository/crud/chat.py
  backend/src/repository/events.py
  backend/src/repository/rag_datasets_eng.py
  backend/src/utilities/formatters/__init__.py
  backend/src/utilities/formatters/ds_formatter.py
Labels: apis

#306 Add roadmap and replace ds_formatter location
  README.md
  backend/src/utilities/formatters/__init__.py
  backend/src/utilities/formatters/ds_formatter.py
Labels: documentation

#322 fix rag search and context issue
  backend/src/api/routes/chat.py
  backend/src/repository/rag/chat.py
  backend/src/repository/vector_database.py
Labels: apis

#323 fix db async session in process issue
  backend/src/api/dependencies/session.py
  backend/src/api/routes/rag_datasets.py
  backend/src/repository/crud/vectors_helper.py
  backend/src/repository/database.py
Labels: apis

#328 Add doc
  README.md
  docs/Requirements.md
Labels: documentation
